### ISSUE TITLE
Log to Coralogix

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#126]
If token provided.

**Comment by tripodsan** [comment]
where, what, why, how?

**Comment by trieloff** [comment]
# Where
- from the Fastly Gateway

# What
- [ ] timestamps start/end
- [ ] selected runtime
- [ ] parameters
- [ ] request/response size
- [ ] transaction id
- [ ] status code
- [ ] ...

# Why
- to understand if universal runtime is calling the correct underlying runtime
- to increase visibility

# How
- move the JSON log formatting DSL from `helix-logging` to `fastly-native-promises`
- use the add logger function to add a remote log config when setting up a gateway config on Fastly
