### ISSUE TITLE
Automatic Epsagon / Status configuration

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#148]
with the original, pure openwhisk deployments, each action defines usually the epsagon and status wrappers.
the benefit is that they can be additionally be configured. furthermore, the status was usually wrapped before epsagon, so that the status pings don't generate epsagon traces.

eg:

```js
module.exports.main = wrap(main)
  .with(epsagon)
  .with(helixStatus)
  .with(logger.trace)
  .with(logger);
```

with the universal approach, we cannot have a universal epsagon integration, as it is not recommended by epsagon.
currently, the epsagon wrappers are enabled directly in the adapter, hence also record traces for status pings

if it should be avoided to record traces for status pings, either move the status wrapper also to the adapter, or try to delay the epsagon init until it is wrapped in the function again.

### epsagon stubs in adapter

the adapter would create a epsagon initialization handler but delay the execution until it is needed by the action. the problem is that the different epsagon wrappers (openwhisk, lambda, ...) expect the respective signature of the runtime handler (`main(params)` or `handler(event)`, etc). so the only way would probably be to restart the execution and skip the wrappers before. however, this is all a bit complicated and error prone.

### move helix status to adapter and allow configuration

the helix-status wrapper could also happen in the adapter and allow the action to configure it.
eg:

```js
module.exports.main = wrap(main)
  .with(logger.trace)
  .with(logger);

main.plugins = {
  status: {
    plugin: helixStatus,
    github: 'https://raw.githubusercontent.com/adobe/helix-static/master/src/index.js' 
  }
}
```

or even a more generic approach, that allows to define and configure all the wrappers in the action,
but allows the adapter to _install_ them.

```js
module.exports.main = main;

main.plugins = [{
  require('@adobe/helix-epsagon'),
  {
    plugin: require('@adobe/helix-status'),
    config: {
      github: 'https://raw.githubusercontent.com/adobe/helix-static/master/src/index.js' 
   },
  logger.trace,
  logger,
];
```

**Comment by trieloff** [comment]
I'd go with the more generic approach you suggested.

**Comment by tripodsan** [comment]
I tried to implement it...the problem is when we move the plugins to the adapter level, they all need to be runtime aware and can't be universal again. epsagon is an exception that it can't be universal, since they need to wrap the original handler/action. 

alternatively, we could try to pass down the original invocation arguments in the `context` and then simulate the respective signature again for epsagon....

**Comment by trieloff** [comment]
What if we have two extension points that plugins could hook into? Pre-wrapped (epsagon) and post-wrapped (status)

**Comment by tripodsan** [comment]
if we still want to avoid tracing status pings, then this doesn't help. 

also, it is awkward from the perspective of an action, that is can provide a pre-wrapped plugin.
then, i'd rather just have the configuration during deploy: `--no-espagon`

**Comment by tripodsan** [comment]
won't fix.
