### ISSUE TITLE
Google validate/ready sequence broken

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#170]
> This PR completely breaks the Google deployer. It also deactivates it and disables the tests, so it is hard to notice.
>
> Previously, the deployer would work, even if only the key JSON was specified as the key JSON contained the email and project, this is no longer the case.
>
> Even without this check, `init` is never called, so that `this._client` won't get initialized.

_Originally posted by @trieloff in https://github.com/adobe/helix-deploy/pull/168#issuecomment-803976483_

**Comment by tripodsan** [comment]
as I wrote in the PR, only when all conditions are met, the auto-deploy should activate.
it can not be, that the auto-deploy enables google, but then fails because of a precondition is failing.

it can only fail, if specifically `--target=google` is specified.
