### ISSUE TITLE
AWS: functions should log to Coralogix

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-deploy#192]
We currently have no logs of functions deployed on AWS in Coralogix. Now that the majority of traffic has been moved to AWS It's impossible to investigate issues like e.g. 5xx errors. We're practically running production in blind flight.

### Expected Behaviour

AWS functions should log to Coralogix.

### Actual Behaviour

No logs in Coralogix, Cloudwatch logs are a pain to use and search (even those familiar with AWS and Cloudwatch seem to have trouble finding relevant log msgs). 

#### Steps to Reproduce

Look for logs of functions deployed on AWS ...

### Discussions

https://adobeio.slack.com/archives/CGG9B79BK/p1613553793071100?thread_ts=1613548025.066400&cid=CGG9B79BK

**Comment by tripodsan** [comment]
logs are sent to coralogix:

![image](https://user-images.githubusercontent.com/917628/113268164-0fe08980-9312-11eb-9337-48508086aff9.png)

here 2 hours of logs. the `lqmig3v5eb` are the ones from AWS

**Comment by stefan-guggisberg** [comment]
Thanks for the clarifications, closing
