### ISSUE TITLE
Log more details of unexpected response: no headers

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#194]
In the last 7 days, we have seen this error 150 times (about 50 from helix-dispatch and 100 from content-proxy)

https://github.com/adobe/helix-deploy/blob/d9ba93bb769d2cadd5deaaf84f5be2571098675c/src/template/utils.js#L41

it would be great to get more detail to see what is causing this error.

**Comment by tripodsan** [comment]
maybe the response really doesn't have headers....

**Comment by trieloff** [comment]
It's probably not a response, but we could at least log the `typeof` and the `Object.keys` of whatever it is.
