### ISSUE TITLE
separate cli from utils

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#2]
ideally, the cli and the library that will be used by the _actions_ should be in 2 different packages

- helix-deploy contains the cli for building the universal zip
- helix-universal (TBD) contains:
   - adapters for each target platform
   - instrumentation for espagon for each target platform
   - instrumentation for setting up logging
   - ( implementation of `Request`, `Response` and `Context` )

the `template/index.js` in `helix-deploy` would then only import the adapters from the library.

**Comment by tripodsan** [comment]
actually, I'm not sure anymore if epsagon, status and logging should be part of this library. they should just work with the adapters :-)

**Comment by trieloff** [comment]
Status and logging would need refactoring to support the new function signature. For epsagon, I'm not sure.

**Comment by tripodsan** [comment]
@trieloff I think we should now separate the 2:

- Create a new library `helix-universal` that contains all the adapter code.
- we can also re-export `Request` and `Response` or add it as required peer dependency.
- add the `helix-universal` as required peer dependency also to helix-deploy, so that services are forced to import them.

this has the advantage, that the services can then properly add the library as dependency (as opposed to a dev dependency).
