### ISSUE TITLE
Include Backend URL in Gateway Response

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#22]
let's say you have https://unviersal.runtime.com/helix-services/git-resolve-ref... and it is routed to AZURE and fails.
so it's probably important to include the backend request url in the response....

_Originally posted by @tripodsan in https://github.com/adobe/helix-deploy/issues/20#issuecomment-745001907_

**Comment by tripodsan** [comment]
@trieloff how is this fixed by #20 ?
