### ISSUE TITLE
Support ESM-based functions

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#227]
We have a number of dependencies that are migrating from commonjs to ESM. ESM is supported in Node 12 and it can import CommonJS modules, but not vice versa. We should evaluate what it takes to deploy an example function written using ESM to the four supported clouds.

Chance is that the webpacking step can take care of some of the complications, but not all of them.

**Comment by tripodsan** [comment]
note, that esm is still in the experimental state for node 12. even for node 14:

> As of Node.js 14 there is no longer this warning when using ESM in Node.js. However, the ESM implementation in Node.js remains experimental. As per our stability index: “The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release.” Users should be cautious when using the feature in production environments.

So running pure ESM code might be "risky". I think a better alternative is to use babel+webpack. this combination is tested very well.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-home/discussions/193

**Comment by tripodsan** [comment]
esm+webpack solution works with #229
