### ISSUE TITLE
Cleanup old functions?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#232]
Google has a hard limit of 1.000 functions per project and region. I just noticed because we are now hitting the limit.

We may need some feature to clean up old versions, but I'm not yet sure how to specify what an old version would be.

**Comment by trieloff** [comment]
We create three new flags: `--cleanup-ci=1 --cleanup-patch=7 --cleanup-minor=30 --cleanup-major=365`. Each flag specifies the maximum number of days that redundant versions of the same scope will be kept.

e.g. for the following versions of `word2md`

```
helix-services--word2md_2_6_0   2021-04-06T08:13:03.192Z
helix-services--word2md_2_6_1   2021-04-08T03:35:28.669Z
helix-services--word2md_2_7_0   2021-04-09T04:27:02.983Z
helix-services--word2md_2_7_1   2021-04-12T02:17:29.575Z
helix-services--word2md_2_7_2   2021-04-12T07:34:56.362Z
helix-services--word2md_2_7_3   2021-04-12T16:39:58.929Z
helix-services--word2md_2_7_4   2021-04-13T02:32:52.661Z
helix-services--word2md_2_8_0   2021-04-13T08:54:24.344Z
helix-services--word2md_2_8_1   2021-04-13T09:16:39.893Z
helix-services--word2md_2_8_2   2021-04-15T06:57:09.015Z
helix-services--word2md_2_8_3   2021-04-15T14:33:55.612Z
helix-services--word2md_2_8_4   2021-04-19T03:58:33.314Z
helix-services--word2md_2_8_5   2021-04-20T03:13:47.946Z
```

A `--cleanup-patch=7` will consider all versions older than 7 days (2021-04-13) and remove each version that has a higher existing patch version at the same major and minor version, so that

```
helix-services--word2md_2_8_0   2021-04-13T08:54:24.344Z
helix-services--word2md_2_8_1   2021-04-13T09:16:39.893Z
  => since helix-services--word2md_2_8_5 (current version) exists

helix-services--word2md_2_7_0   2021-04-09T04:27:02.983Z
helix-services--word2md_2_7_1   2021-04-12T02:17:29.575Z
helix-services--word2md_2_7_2   2021-04-12T07:34:56.362Z
helix-services--word2md_2_7_3   2021-04-12T16:39:58.929Z
  => since helix-services--word2md_2_7_4 exists

helix-services--word2md_2_6_0   2021-04-06T08:13:03.192Z
  => since helix-services--word2md_2_6_1 exists
```

**Comment by tripodsan** [comment]
I don't think we need to keep so many old versions. I would only keep the last 3 recent production ones, and 3 recent ci ones.
we don't have (and probably never will) any special customers that need to use old versions.
