### ISSUE TITLE
Package parameters not supported in Lambda

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#3]
We'd need to find some alternative, e.g. https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html

[Caveats](https://medium.com/better-programming/how-to-store-your-aws-lambda-secrets-cheaply-without-compromising-scalability-or-security-d3e8a250f12c):

> Another neat feature is the ability to retrieve the parameters at runtime. This is nice — it decouples deployment and configuration. If you want to do this, here’s a helper gist I wrote that smooths the process for node Lambdas.
> However, Parameter Store has a drawback: the throughput is very low. Each parameter retrieved with get-parameters counts as one request and you’re only allowed 100 requests per second.
> You can increase this limit, but doing so raises the price, and still only allows 1,000 requests per second.

**Comment by tripodsan** [comment]
i'd prefer the secrets manager; but it has the same caveat.

**Comment by tripodsan** [comment]
> Each parameter retrieved with get-parameters counts as one request and you’re only allowed 100 requests per second.

but you can fetch _all_ of them at once:
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html

**Comment by tripodsan** [comment]
I tried it out:

```js
const { promisify } = require('util');
const AWS = require('aws-sdk')

AWS.config.update({
    region: 'us-east-1'
})

const ssm = new AWS.SSM()

ssm.getParameter = promisify(ssm.getParameter.bind(ssm));
ssm.getParametersByPath = promisify(ssm.getParametersByPath.bind(ssm));

exports.handler = async (event, context) => {
    const t0 = Date.now();
    const param = await ssm.getParameter({
        Name: '/helix-pages/simple-package/foo-token',
        WithDecryption: true,
    });
    const t1 = Date.now();
    console.log(param, t1-t0);
    const params = await ssm.getParametersByPath({
        Path: '/helix-pages/simple-package/',
        WithDecryption: true,
    });
    const t2 = Date.now();
    console.log(params, t2-t1);
    return {
        statusCode: 200,
        body: JSON.stringify(param)
    };
};
```

gives:
```
2020-12-11T08:59:45.165Z	4a929556-addf-44a1-b248-b2f143d408b7	INFO	{
  Parameter: {
    Name: '/helix-pages/simple-package/foo-token',
    Type: 'SecureString',
    Value: 'secure foo token',
    Version: 1,
    LastModifiedDate: 2020-12-11T08:03:09.529Z,
    ARN: 'arn:aws:ssm:us-east-1:010606261767:parameter/helix-pages/simple-package/foo-token',
    DataType: 'text'
  }
} 346
2020-12-11T08:59:45.313Z	4a929556-addf-44a1-b248-b2f143d408b7	INFO	{
  Parameters: [
    {
      Name: '/helix-pages/simple-package/another-token',
      Type: 'SecureString',
      Value: 'another secret token vlaue',
      Version: 1,
      LastModifiedDate: 2020-12-11T08:03:51.659Z,
      ARN: 'arn:aws:ssm:us-east-1:010606261767:parameter/helix-pages/simple-package/another-token',
      DataType: 'text'
    },
    {
      Name: '/helix-pages/simple-package/foo-param',
      Type: 'String',
      Value: 'unsecured config param.',
      Version: 1,
      LastModifiedDate: 2020-12-11T08:02:32.343Z,
      ARN: 'arn:aws:ssm:us-east-1:010606261767:parameter/helix-pages/simple-package/foo-param',
      DataType: 'text'
    },
    {
      Name: '/helix-pages/simple-package/foo-token',
      Type: 'SecureString',
      Value: 'secure foo token',
      Version: 1,
      LastModifiedDate: 2020-12-11T08:03:09.529Z,
      ARN: 'arn:aws:ssm:us-east-1:010606261767:parameter/helix-pages/simple-package/foo-token',
      DataType: 'text'
    }
  ]
} 147
```

--> *147ms* overhead to read the params... not too bad, I think

**Comment by trieloff** [comment]
Looks good:
- the `aws-sdk` is pre-installed, so we can just add the code to the wrapper without blowing up dependency size for other projects
- we should keep the parameters in the global scope, so that they stay cached until the container gets destroyed
- we should be lazy loading only the parameters that are really needed to reduce the number of requests. With 50 parameters in a package, we can only afford two cold starts per second before we hit the rate limit

The biggest downside I see is that you'd have to `await context.env['foo-param']` an access to SSM is async.

**Comment by tripodsan** [comment]
> * we should be lazy loading only the parameters that are really needed to reduce the number of requests

but with `getParametersByPath()` we can load all of them at once.

**Comment by trieloff** [comment]
But each parameter would count as one request, even if we retrieve them in batch.

**Comment by tripodsan** [comment]
> But each parameter would count as one request, even if we retrieve them in batch.

I don't think so. it's one request.
