### ISSUE TITLE
AWS: add tool to cleanup temp buckets

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#33]
after and action is deployed, its temp bucket is usually automatically deleted. but if an error occurs or the cli is aborted, the temp buckets accumulate. deleting them via the AWS console is tedious.

![image](https://user-images.githubusercontent.com/917628/102703754-40963900-42b6-11eb-85a4-4ad25c49c47d.png)

# suggest
add `--aws-cleanup-buckets` command that deletes the tmp buckets.

**Comment by trieloff** [comment]
I'd enable this by default if the AWS credentials are there.

**Comment by tripodsan** [comment]
> I'd enable this by default if the AWS credentials are there.

I don't think this is a good idea. There is a chance that a bucket is deleted while it is used for deployment. eg when many CIs a running. usually, the jobs complete and the buckets are deleted by the deploy function.
