### ISSUE TITLE
upgrade azure/appservices to v11 or remove support

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#355]
with v10, the azure appservices did a major API change which requires bigger changes in the `AzureDeployer`

either:
- update (see https://github.com/Azure/azure-sdk-for-js/blob/main/documentation/MIGRATION-guide-for-next-generation-management-libraries.md)
- or remove support for azure

**Comment by tripodsan** [comment]
+1 to remove azure suppport

**Comment by trieloff** [comment]
Removing Azure support is probably the right thing to do, given the overall immaturity of the stack and the low likelihood of usage.

**Comment by tripodsan** [comment]
I gladly take care of it :-)
