### ISSUE TITLE
AWS: problem with routes/integration limits per API Gatway

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#45]
The AWS API Gateway has limits on how many routes/integrations can be added to 1 API:

https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-limits:

Resource or operation | Default quota | Can be increased
-- | -- | --
Routes per API | 300 | Yes
Integrations per API | 300 | No
Maximum integration timeout | 30 seconds | No

the current way maps 2 routes to 1 integration to 1 lambda (helix service version):

```
/helix-services/foo_1.8.3/        -----> integration:1234  ----> function:my-function:1.8.3
/helix-services/foo_1.8.3/{path+} --/
```

when (sym)linking release versions, there are more routes, eg:

```
/helix-services/foo_1.8.3/ ------------> integration:1234  ----> function:my-function:1.8.3
/helix-services/foo_1.8.3/{path+} ----/
                                     /
/helix-services/foo_v1 -------------/
/helix-services/foo_v1{path+} -----/
/helix-services/foo_v1.8----------/
/helix-services/foo_v1.8{path+} -/
```

Assuming having 30 helix services with the current scheme, would only allow 10 versions per service. Those could be consumed very quickly, especially with CI testing.

### Reduce amount of versions by using different API for CI

problem:
- inter-action routing will be difficult if CI versions and prod version should be tested together. eg: `dispatch@ci1234 ---invokes---> static@v1`.

### Create API Per service and use custom domains

1 service is managed by 1 AWS API Gateway, eg:  https://resolve-git-ref.helix-services.helix.com/v1.8

problem: 
- fastly has by default 5 backends. AWS APIs are managed by different hosts, i.e. host-header override doesn't work.
- inter-action routing would invoke API on different hosts, which is problematic

### Create global multiplex function

Having one multiplex function that uses the [invoke] api. there could be 1 function per package, eg:

```
ANY /helix-services/{name}
ANY /helix-services/{name}/{path+}
```

problem:
- potentially slower
- potentially many too many invocations to 1 function

### Hybrid: 1 Multiplex function per service with symlink routes

Having a multiplex function per service would reduce the amount of traffic to that function. using routes only for the symlinks would keep the production functions fast.

eg:

```
/helix-services/foo/{version}  ------------> integration:multiplex  ----> function:multiplex:1.0
/helix-services/foo/{version}/{path+} ----/
                                     
/helix-services/foo/v1 --------------------> integration:foo ---> function:foo:1.8.1
/helix-services/foo/v1/{path+} -----------/
/helix-services/foo/v1.8 ----------------/
/helix-services/foo/v1.8/{path+} -------/
```

The multiplex function would then [invoke] the respective lambda directly, eg:

```
POST /2015-03-31/functions/helix-services--resolve-git-ref:ci1234/invocations
```

This would limit the number of integrations to 1 per (released) service. it would also be possible to keep the last 2-3 integrations, so that switching the routes back to the last-known-good would still be fast.

needs #44 

[invoke]: https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

**Comment by tripodsan** [comment]
quick test:

routes:

![image](https://user-images.githubusercontent.com/917628/103136835-28377b80-4707-11eb-9efb-d60c9a6a0566.png)

example requests:

```
$ curl -sD - https://qh5ed1bzha.execute-api.us-east-1.amazonaws.com/toby-test/v3 | fgrep routeKey
  "routeKey": "ANY /toby-test/v3",
    "routeKey": "ANY /toby-test/v3",
$ curl -sD - https://qh5ed1bzha.execute-api.us-east-1.amazonaws.com/toby-test/v3/foo | fgrep routeKey
  "routeKey": "ANY /toby-test/v3/{path+}",
    "routeKey": "ANY /toby-test/v3/{path+}",
$ curl -sD - https://qh5ed1bzha.execute-api.us-east-1.amazonaws.com/toby-test/1.8.1 | fgrep routeKey
  "routeKey": "ANY /toby-test/{version}",
    "routeKey": "ANY /toby-test/{version}",
$ curl -sD - https://qh5ed1bzha.execute-api.us-east-1.amazonaws.com/toby-test/1.8.1/foo | fgrep routeKey
  "routeKey": "ANY /toby-test/{version}/{path+}",
    "routeKey": "ANY /toby-test/{version}/{path+}",
```

**Comment by trieloff** [comment]
Hybrid 1 seems worth trying

**Comment by tripodsan** [comment]
added proxy function directly to aws:

![image](https://user-images.githubusercontent.com/917628/105149459-e69fc200-5b46-11eb-9535-cb72274bad2c.png)


```js
const AWS = require('aws-sdk');
const { promisify } = require('util');

exports.handler = async (event, context) => {
    const lambda = new AWS.Lambda();
    const invoke = promisify(lambda.invoke.bind(lambda));

    const { action, version, path } = event.pathParameters;
    const FunctionName = `helix-services--${action}:${version.replace(/\./g, '_')}`;

    try {
        console.log('invoking', FunctionName);
        const ret = await invoke({
            FunctionName,
            Payload: JSON.stringify(event),
        });
        return JSON.parse(ret.Payload);
    } catch (err) {
        console.error(err);
        return {
            statusCode: err.statusCode,
            body: err.message,
        }
    }
};
```

todo:
- [ ] add hedy argument to setup proxy function on new API
- [ ] add to helix-pages
