### ISSUE TITLE
allow webpack configuration to be customized per project

### ISSUE THREAD

**Issue by justinedelson** [adobe/helix-deploy#641]
### Expected Behaviour

There should be a way to customize the webpack configuration used by helix-deploy, e.g. to add plugins.

### Actual Behaviour

There isn't :(

### Reproduce Scenario (including but not limited to)

I have a use case where I need to modify the webpack-bundled code to add instrumentation. The task can be done with a webpack plugin although there's no place (at least that I can see) to inject that into the webpack config.

**Comment by tripodsan** [comment]
what exactly is your use case? I think that replacing the entire webpack config is probably not very helpful, as it contains many internal logic.

**Comment by justinedelson** [comment]
My (current) use case is adding a plugin. It is certainly plausible to have an extension point that _only_ does this, but I was aiming for something that didn't have to be revisited later.
