### ISSUE TITLE
split development-server from the cli

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#654]
having the dev server in helix-deploy is convenient to use, but a nightmare for releasing, since the cli and the dev server have independent release cycles. i.e. fixing a bug in the development server causes updates in many projects that don't need it.

suggest to move the development server in it's own package, either:

1) create a new repository: helix-universal-devserver

2) or turn this into a monorepo with 2 packages: helix-deploy and helix-universal-devserver

I'd probably go with 2), so we can later modularize more, e.g. split by deployers, to make even leaner builds.

**Comment by trieloff** [comment]
You are the main user of the dev server, so I'm ok with splitting it. However, I'm seeing your monorepo pain with helix-shared and won't allow you to make the same mistake twice, so +0 to 1 and -1 to 2

**Comment by tripodsan** [comment]
> and won't allow you to make the same mistake twice

but now I've learned and know what i'm doing :-)

**Comment by tripodsan** [comment]
@trieloff https://github.com/adobe/helix-home/issues/376
