### ISSUE TITLE
[cloudflare] restore cloudflare worker script settings after deploy

### ISSUE THREAD

**Issue by maxakuru** [adobe/helix-deploy#707]
cloudflare worker deploy uses the [upload worker module API](https://developers.cloudflare.com/api/operations/worker-script-upload-worker-module) which overwrites settings such as `logpush`

we should add argument(s) to set cloudflare worker settings for the cloudflare target, at least for `logpush` but potentially for other worker settings

one option is to add `--cloudflare-setting-{key}` for the primitive value settings, for example `--cloudflare-setting-logpush true` to enable logpush

**Comment by maxakuru** [comment]
[patch worker settings API](https://developers.cloudflare.com/api/operations/worker-script-patch-settings) for future reference

**Comment by trieloff** [comment]
I see two options here that could preserve the settings:
1. prior to the `PUT` we `GET` https://developers.cloudflare.com/api/operations/worker-script-settings-get-settings (guard against 404) and then only update the script contents with https://developers.cloudflare.com/api/operations/worker-script-put-content
2. same, but we use this `PUT` https://developers.cloudflare.com/api/operations/worker-script-upload-worker-module and replicate the settings that we just `GET`ed (got) 

This would not require us to add more settings and could simplify the patch a bit.

**Comment by maxakuru** [comment]
looking more at this.. that makes sense, avoiding many extra settings and potentially being out of sync with CF

since `params` are uploaded alongside the worker module, and it's possible someone adds a param after the initial deploy, I think it makes sense to go with your 2nd suggestion
