### ISSUE TITLE
Gateway does not include package name in URL

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#80]
In an oversight, I hardcoded the package name into the gateway config, conflating namespace and package name.

Right now, a user can pick a combination of namespace and package name by changing the hostname and pick the action name through the path.

I propose a change where the the URL is composed of:

```
https://${namespace}.anywhere.run/${package}/${action}/…
```

This would be a breaking change, but one with low impact, as no one is using the Gateway'd URLs yet.

**Comment by tripodsan** [comment]
what about even decouple the version:

```
https://${namespace}.anywhere.run/${package}/${action}/${version}…
```

**Comment by trieloff** [comment]
With an `@`?

```
https://${namespace}.anywhere.run/${package}/${action}@${version}…
```

**Comment by tripodsan** [comment]
> With an `@`?
> 
> ```
> https://${namespace}.anywhere.run/${package}/${action}@${version}…
> ```

well, that's we currently use for openwhisk actions...but the `@` is a problem anyways in AWS routes...so maybe have the anywhere url be more flexible.

**Comment by trieloff** [comment]
I can easily replace the `@` in the URL with an `_` or anything like that in VCL. In general, I like the URL format we have in OW, except for the long prefix.
