### ISSUE TITLE
Provide easy check for production/simulator environment

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#90]
```javascript
    return Boolean(process.env.__OW_ACTIVATION_ID) || Boolean(process.env.AWS_LAMBDA_FUNCTION_NAME);
```

> I'd prefer to have something in the wrapper, but it's good for now.

_Originally posted by @trieloff in https://github.com/adobe/helix-pipeline/pull/947#discussion_r566130708_

**Comment by tripodsan** [comment]
currently, it seems still to be active, IIRC, the pipeline logs should only be written in local dev:

```
2021-03-29T23:00:01.565+09:00 | [ERROR] Exception during #32/error:report from /var/task/index.js:8133:
-- | --
  | 2021-03-29T23:00:01.565+09:00 | Error: ENOENT: no such file or directory, mkdir '/var/task/logs'
```
